### ISSUE TITLE
可不可以发送到邮箱什么的

### ISSUE THREAD

**Issue by zuikea** [No5972/pixiv-github-action#3]
请问这个可以可以实现利用GitHub Actions自动发送爬取到的图片到邮箱，或者转到网盘之类的d

**Comment by No5972** [comment]
It's not hard to send emails. You can just search "email" in the marketplace of GitHub and simply configure it, then GitHub will automatically send the crawled pictures to your mail box.

As for cloud storages, there are limit storages that are supported. Currently only Google Drive is supported.

**Comment by Clancy6** [comment]
[试试gmx.com](gmx.com)提供的邮箱吧，代码参考：https://lians.netlify.app/file/lizhiMailBot-main.zip
