### ISSUE TITLE
Upload to this repo

### ISSUE THREAD

**Issue by Lanlinan** [No5972/pixiv-github-action#5]
纯小白不太懂，弄了好久都没成功
https://github.com/Lanlinan/pixiv-github-action/actions/runs/3883575672/jobs/6625042694#step:8:60
![image](https://user-images.githubusercontent.com/74476627/211563490-58cbd682-bb31-4d36-8c04-2be58c16f4d2.png)

**Comment by No5972** [comment]
Try creating a branch ```result``` in your repo webpage. (Modify any file in the branch ```runner``` and then select "Create a new branch for this commit and start a pull request. " and then type ```result``` in the text box below)
